"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = ["src/img/icon_open.png",
                "src/img/icon_histogram.png",
                "src/img/cursor_paint.png",
                "src/img/icon_mask.png",
                "src/img/icon_redo.png",
                "src/img/icon_save.png",
                "src/img/icon_undo.png",
                "src/img/cursor_crop.png",
                "src/img/icon_pencil.png",
                "src/img/icon_crop.png",
                "src/img/icon_dropdown.png",
                "src/img/icon_auto.png",
                "src/style.css",
                "model.h5",
                "src/segment_image.py",
                "src/lib.py",
                "src/handle_event.py",
                "src/gui.py"
                ]
OPTIONS = {
    'packages':['tensorflow', "keras", "numpy", "cv2", "PyQt5", "matplotlib"]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
